spring:
  application:
   #服务名称
    name: service-zuul
server:
  port: 8769

eureka:
  client:
   #注册地址
    service-url:
      defaulZone: http://localhost:8761/eureka/
zuul:
  #路由配置
  routes:
   #1 以api-a开头的请求都转发给service-ribbon服务
   api-a:
     path: /api-a/**
     serviceId: service-ribbon
   #2 以api-b开头的请求都转发给service-feign服务
   api-b:
     path: /api-b/**
     serviceId: service-feign
   #3 以api-c开头的请求都转发给client1服务
   api-c:
     path: /api-c/**
     serviceId: client1